services:
  mysqldb:
    image: mysql:8.0.34
    container_name: tournamentdatabase
    volumes:
      - ./server/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      DB_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tournament
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    networks:
      - dockerbridge
  api:
    image: tournamentapi:1.0
    build: server/.
    container_name: tournamentapi
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      DB_HOST: mysqldb
      DB_USER: "admin"
      DB_PASSWORD: "password"
      DB_NAME: "tournament"
      DB_PORT: "3306"
    depends_on:
      - mysqldb
    networks:
      - dockerbridge
networks:
  dockerbridge:
    driver: bridge